### ISSUE TITLE
Glitches on the screen and update info When Using Orca direct Print or Cura Direct Print

### ISSUE THREAD

**Issue by navaismo** [navaismo/OctoPrint-E3v3seprintjobdetails#3]
Since people is not only using the default Octoprint UI to Load -> Analyze -> Print a Gcode file, but using slicers like Orca or Cura to make a direct connection to the Server, the "normal flow" is broken and the Plugin send mixed information or not information at all. 

This is causing:

- Glitches in the LCD.
- Overlapping Menus
- Not info updated at all. 

In the issue #2 @krvwag Proposed a PR with a good solution for Orca direct Print; but the event "MetadataAnalysisFinished" is causing many issues on the normal GUI when loading or uploading files. Also when using Cura the event is causing glitches.

Need to apply a logic that will work for the different flows of sending a job to print:

1. From Orca: Upload, Analyze, Print.
2. From Cura: Upload, Select, Analyze, Print.
3. From GUI:  Upload, Load, Print.
4. From GUI:  Upload, Direct Print.
5. From GUI:  Direct Print of a previous Saved File.
6. From GUI:  Select, Print a previos Saved File.
7. Cancel Job from any source.

also issue ref: https://github.com/navaismo/Ender-3V3-SE/issues/1

**Comment by krvwag** [comment]
If the event "MetadataAnalysisFinished" causes too many problems it can be removed again.

**Comment by navaismo** [comment]
No, no worries. I think its a good start to have a plugin that works in different escenarios.

I'm working on it and will release another version to see if works.

**Comment by navaismo** [comment]
Released the version 0.1.0 to see if fixes the flows please test and report.

**Comment by navaismo** [comment]
Seems that is working now. Closing this.
